default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= Rails.application.credentials.dig(:database, :username)  %>
  password: <%= Rails.application.credentials.dig(:database, :password) %>

development:
  primary:
    <<: *default
    database: peach_cars

  legacy:
    <<: *default
    database: peach
    username: <%= Rails.application.credentials.dig(:legacy_db, :username)  %>
    password: <%= Rails.application.credentials.dig(:legacy_db, :password) %>

test:
  primary:
    <<: *default
    database: peach_cars_test
  
  legacy:
    <<: *default
    database: peach_cars_test
    username: <%= Rails.application.credentials.dig(:legacy_db, :username)  %>
    password: <%= Rails.application.credentials.dig(:legacy_db, :password) %>


production:
  primary:
    <<: *default
    host: <%= ENV["PROD_DB_HOST"] %>
    database: <%= ENV["PROD_DB_NAME"] %>
    username: <%= ENV["PROD_DB_USERNAME"] %>
    password: <%= ENV["PROD_DB_PASSWORD"] %>

  replica:
    host: <%= ENV["READ_REPLICA_HOST"] %>
    port: 5432
    username: <%= Rails.application.credentials.dig(:database, :replica_username) %>
    password: <%= Rails.application.credentials.dig(:database, :replica_password) %>
