default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["DEV_DB_USERNAME"] %>
  password: <%= ENV["DEV_DB_PASSWORD"] %>

development:
  primary:
    <<: *default
    database: peach_cars

  legacy:
    <<: *default
    database: peach
    username: <%= ENV["DEV_DB_USERNAME"] %>
    password: <%= ENV["DEV_DB_PASSWORD"] %>
    database_tasks: false

test:
  primary:
    <<: *default
    database: peach_cars_test
  
  legacy:
    <<: *default
    database: peach
    username: <%= ENV["DEV_DB_USERNAME"] %>
    password: <%= ENV["DEV_DB_PASSWORD"] %>
    database_tasks: false


production:
  primary:
    <<: *default
    host: <%= ENV["PROD_DB_HOST"] %>
    database: <%= ENV["PROD_DB_NAME"] %>
    username: <%= ENV["PROD_DB_USERNAME"] %>
    password: <%= ENV["PROD_DB_PASSWORD"] %>
  

  replica:
    host: <%= ENV["REPLICA_HOST"] %>
    port: 5432
    username: <%= ENV["REPLICA_DB_USERNAME"] %>
    password: <%= ENV["REPLICA_DB_PASSWORD"] %>

  legacy:
    <<: *default
    database: <%= ENV["LEGACY_DB_NAME"] %>
    host: <%= ENV["LEGACY_HOST"] %>
    username: <%= ENV["LEGACY_DB_USERNAME"] %>
    password: <%= ENV["LEGACY_DB_PASSWORD"] %>
    database_tasks: false