default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= Rails.application.credentials.dig(:database, :username)  %>
  password: <%= Rails.application.credentials.dig(:database, :password) %>

development:
  <<: *default
  database: peach_cars

  replica:
    - host: localhost
      port: 5432
      username: <%= Rails.application.credentials.dig(:database, :replica_username) %>
      password: <%= Rails.application.credentials.dig(:database, :replica_password) %>
      database: peach

test:
  <<: *default
  database: peach_cars_test

production:
  <<: *default
  database: peach_cars_production
  username: pch_website_rails_inertia
  password: <%= ENV["PCH_WEBSITE_RAILS_INERTIA_DATABASE_PASSWORD"] %>

  replicas:
    - host: <%= ENV["READ_REPLICA_HOST"] %>
      port: 5432
      username: <%= Rails.application.credentials.dig(:database, :replica_username) %>
      password: <%= Rails.application.credentials.dig(:database, :replica_password) %>

